export const env_var = {
  JWT_SECRET: process.env.JWT_SECRET,
  DATABASE_KEY: process.env.DATABASE_KEY,
  CELLFILE_4G_ID: process.env.CELLFILE_4G_ID,
  CELLFILE_5G_ID: process.env.CELLFILE_5G_ID,
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
  GOOGLE_SERVICE_ACCOUNT: process.env.GOOGLE_SERVICE_ACCOUNT,
  AWS_USER_ACCESS_KEY: process.env.AWS_USER_ACCESS_KEY,
  AWS_USER_SECRET_ACCESS_KEY: process.env.AWS_USER_SECRET_ACCESS_KEY,
  AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
  AWS_BUCKET_REGION: process.env.AWS_BUCKET_REGION
};
